package webhook

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const CurrentSchemaVersion uint = 1

//go:embed schema/*.sql
var schemaFiles embed.FS

type Migration struct {
	Version uint
	Digest  string
	UpSQL   string
	DownSQL string
}

type WrittenMigration struct {
	UpPath   string
	DownPath string
	Digest   string
}

func Schema(version uint) (Migration, error) {
	if version != CurrentSchemaVersion {
		return Migration{}, fmt.Errorf("webhook: unsupported schema version %d", version)
	}
	up, err := schemaFiles.ReadFile("schema/v1.up.sql")
	if err != nil {
		return Migration{}, fmt.Errorf("webhook: read up schema: %w", err)
	}
	down, err := schemaFiles.ReadFile("schema/v1.down.sql")
	if err != nil {
		return Migration{}, fmt.Errorf("webhook: read down schema: %w", err)
	}
	sum := sha256.Sum256(append(append([]byte(nil), up...), down...))
	return Migration{Version: version, Digest: hex.EncodeToString(sum[:]), UpSQL: string(up), DownSQL: string(down)}, nil
}

func WriteMigration(directory, name string, version uint) (WrittenMigration, error) {
	if strings.TrimSpace(directory) == "" {
		return WrittenMigration{}, errors.New("webhook: migration directory is required")
	}
	if strings.TrimSpace(name) == "" || filepath.Base(name) != name {
		return WrittenMigration{}, errors.New("webhook: migration name must be a base filename")
	}
	migration, err := Schema(version)
	if err != nil {
		return WrittenMigration{}, err
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return WrittenMigration{}, fmt.Errorf("webhook: create migration directory: %w", err)
	}
	header := fmt.Sprintf(
		"-- Code generated by foundation webhook; DO NOT EDIT.\n-- webhook-schema-version: %d\n-- webhook-schema-digest: %s\n\n",
		migration.Version, migration.Digest,
	)
	result := WrittenMigration{
		UpPath:   filepath.Join(directory, name+".up.sql"),
		DownPath: filepath.Join(directory, name+".down.sql"),
		Digest:   migration.Digest,
	}
	if err := writeMigration(result.UpPath, []byte(header+migration.UpSQL)); err != nil {
		return WrittenMigration{}, err
	}
	if err := writeMigration(result.DownPath, []byte(header+migration.DownSQL)); err != nil {
		return WrittenMigration{}, err
	}
	return result, nil
}

func writeMigration(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil {
		if string(existing) == string(content) {
			return nil
		}
		return fmt.Errorf("webhook: migration drift at %s", path)
	}
	if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("webhook: read migration %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("webhook: write migration %s: %w", path, err)
	}
	return nil
}
