package httpcontract

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var goPackagePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// GenerateGo renders the mechanical code/status portion of a product error
// package. Product-owned convenience constructors and cause mapping remain
// handwritten at the semantic seam.
func GenerateGo(catalog ErrorCatalog, packageName string) ([]byte, error) {
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	if !goPackagePattern.MatchString(packageName) {
		return nil, errorsf("Go package name %q is invalid", packageName)
	}
	definitions := append([]ErrorDefinition(nil), catalog.Errors...)
	sort.Slice(definitions, func(i, j int) bool { return definitions[i].Code < definitions[j].Code })
	names := make(map[string]string, len(definitions))
	usedNames := map[string]string{}
	for _, definition := range definitions {
		name := goIdentifier(strings.TrimPrefix(definition.Code, catalog.Namespace+"."))
		if definition.GoName != "" {
			name = definition.GoName
		}
		if previous := usedNames[name]; previous != "" {
			return nil, errorsf("error codes %q and %q generate the same Go name %q", previous, definition.Code, name)
		}
		usedNames[name] = definition.Code
		names[definition.Code] = name
	}

	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by foundation httpcontract; DO NOT EDIT.\n\npackage %s\n\n", packageName)
	output.WriteString("import (\n\t\"sort\"\n\n\t\"github.com/yueli-official/foundation/go/problem\"\n)\n\n")
	output.WriteString("const (\n")
	for _, definition := range definitions {
		fmt.Fprintf(&output, "\tCode%s = %q\n", names[definition.Code], definition.Code)
	}
	output.WriteString(")\n\nvar descriptors = map[string]problem.Descriptor{\n")
	for _, definition := range definitions {
		fmt.Fprintf(&output, "\tCode%s: descriptor(Code%s, %d),\n", names[definition.Code], names[definition.Code], definition.Status)
	}
	output.WriteString("}\n\n")
	output.WriteString("func descriptor(code string, status int) problem.Descriptor {\n\treturn problem.MustDescriptor(problem.MustKind(code, status), \"https://errors.yueli.dev/problems/\"+code)\n}\n\n")
	output.WriteString("func DescriptorForCode(code string) (problem.Descriptor, bool) {\n\tvalue, ok := descriptors[code]\n\treturn value, ok\n}\n\n")
	output.WriteString("type CatalogEntry struct { Code string `json:\"code\"`; Status int `json:\"status\"` }\n\n")
	output.WriteString("func Catalog() []CatalogEntry {\n\tresult := make([]CatalogEntry, 0, len(descriptors))\n\tfor code, value := range descriptors { result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()}) }\n\tsort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })\n\treturn result\n}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("httpcontract: format generated Go: %w", err)
	}
	return formatted, nil
}

func goIdentifier(value string) string {
	var result []rune
	upper := true
	for _, current := range value {
		if current == '.' || current == '_' || current == '-' {
			upper = true
			continue
		}
		if upper {
			current = unicode.ToUpper(current)
			upper = false
		}
		result = append(result, current)
	}
	return string(result)
}

func errorsf(format string, args ...any) error {
	return fmt.Errorf("httpcontract: "+format, args...)
}
