package httpcontract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

func GenerateTypeScript(catalog ErrorCatalog, typeName string) ([]byte, error) {
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	if typeName == "" || !regexpTypeName.MatchString(typeName) {
		return nil, errorsf("TypeScript type name %q is invalid", typeName)
	}
	definitions := append([]ErrorDefinition(nil), catalog.Errors...)
	sort.Slice(definitions, func(i, j int) bool { return definitions[i].Code < definitions[j].Code })
	var output bytes.Buffer
	output.WriteString("// Code generated by foundation httpcontract; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export type %sCode =\n", typeName)
	for _, definition := range definitions {
		fmt.Fprintf(&output, "  | %q\n", definition.Code)
	}
	fmt.Fprintf(&output, "\nexport type %s =\n", typeName)
	for _, definition := range definitions {
		fmt.Fprintf(&output, "  | { readonly code: %q; readonly status: %d; ", definition.Code, definition.Status)
		writeTypeScriptParams(&output, definition.Params)
		switch definition.Violations {
		case "required":
			output.WriteString("readonly violations: readonly { readonly pointer: string; readonly code: string; readonly params?: Readonly<Record<string, string | number | boolean | readonly (string | number | boolean)[]>> }[]; ")
		case "optional":
			output.WriteString("readonly violations?: readonly { readonly pointer: string; readonly code: string; readonly params?: Readonly<Record<string, string | number | boolean | readonly (string | number | boolean)[]>> }[]; ")
		default:
			output.WriteString("readonly violations?: never; ")
		}
		output.WriteString("readonly traceId: string }\n")
	}
	fmt.Fprintf(&output, "\nexport const %sPresentation = {\n", lowerFirst(typeName))
	for _, definition := range definitions {
		fmt.Fprintf(&output, "  %q: { messageKey: %q", definition.Code, definition.MessageKey)
		if definition.RecoveryKey != "" {
			fmt.Fprintf(&output, ", recoveryKey: %q", definition.RecoveryKey)
		}
		output.WriteString(" },\n")
	}
	fmt.Fprintf(&output, "} as const satisfies Record<%sCode, { readonly messageKey: string; readonly recoveryKey?: string }>\n", typeName)
	return output.Bytes(), nil
}

var regexpTypeName = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)

func writeTypeScriptParams(output *bytes.Buffer, params map[string]ParameterDefinition) {
	if len(params) == 0 {
		output.WriteString("readonly params?: never; ")
		return
	}
	names := make([]string, 0, len(params))
	for name := range params {
		names = append(names, name)
	}
	sort.Strings(names)
	output.WriteString("readonly params: { ")
	for _, name := range names {
		definition := params[name]
		optional := ""
		if !definition.Required {
			optional = "?"
		}
		fmt.Fprintf(output, "readonly %s%s: %s; ", name, optional, typescriptType(definition.Type))
	}
	output.WriteString("}; ")
}

func typescriptType(value string) string {
	array := strings.HasSuffix(value, "[]")
	base := strings.TrimSuffix(value, "[]")
	if base == "integer" {
		base = "number"
	}
	if array {
		return "readonly " + base + "[]"
	}
	return base
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

type I18nInventory struct {
	SchemaVersion string                 `json:"schemaVersion"`
	Namespace     string                 `json:"namespace"`
	Messages      []I18nInventoryMessage `json:"messages"`
}

type I18nInventoryMessage struct {
	Code        string   `json:"code"`
	MessageKey  string   `json:"messageKey"`
	RecoveryKey string   `json:"recoveryKey,omitempty"`
	Params      []string `json:"params,omitempty"`
}

func GenerateI18nInventory(catalog ErrorCatalog) ([]byte, error) {
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	inventory := I18nInventory{SchemaVersion: "errors.yueli.dev/i18n-inventory/v1", Namespace: catalog.Namespace}
	for _, definition := range catalog.Errors {
		message := I18nInventoryMessage{Code: definition.Code, MessageKey: definition.MessageKey, RecoveryKey: definition.RecoveryKey}
		for name := range definition.Params {
			message.Params = append(message.Params, name)
		}
		sort.Strings(message.Params)
		inventory.Messages = append(inventory.Messages, message)
	}
	sort.Slice(inventory.Messages, func(i, j int) bool { return inventory.Messages[i].Code < inventory.Messages[j].Code })
	result, err := json.MarshalIndent(inventory, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("httpcontract: encode i18n inventory: %w", err)
	}
	return append(result, '\n'), nil
}
