package abuse

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const PostgresSchemaVersion = 1

type WrittenPostgresMigration struct {
	UpPath   string
	DownPath string
	Digest   string
}

func PostgresSchemaUp() string {
	return strings.TrimSpace(`
CREATE TABLE abuse_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    consumer TEXT NOT NULL,
    definition_version BIGINT NOT NULL CHECK (definition_version > 0),
    definition_digest TEXT NOT NULL,
    active_key_version INTEGER NOT NULL CHECK (active_key_version > 0),
    subject_secret BYTEA NOT NULL CHECK (octet_length(subject_secret) = 32),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE abuse_policy_definitions (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    policy_id TEXT NOT NULL,
    revision BIGINT NOT NULL CHECK (revision > 0),
    signature TEXT NOT NULL,
    definition_digest TEXT NOT NULL,
    definition JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, policy_id)
);

CREATE TABLE abuse_meter_states (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    policy_id TEXT NOT NULL,
    subject_key_version INTEGER NOT NULL CHECK (subject_key_version > 0),
    subject_key BYTEA NOT NULL CHECK (octet_length(subject_key) = 32),
    state JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, policy_id, subject_key_version, subject_key)
);

CREATE TABLE abuse_attempt_receipts (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    attempt_id TEXT NOT NULL,
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    action_key TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (disposition IN ('allow', 'challenge', 'reject')),
    resolved_outcome TEXT NOT NULL DEFAULT '',
    default_outcome TEXT NOT NULL DEFAULT '',
    pending_until TIMESTAMPTZ,
    record JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, attempt_id)
);

CREATE INDEX abuse_meter_states_expiry
    ON abuse_meter_states (instance_key, expires_at);
CREATE INDEX abuse_attempt_receipts_expiry
    ON abuse_attempt_receipts (instance_key, expires_at);
CREATE INDEX abuse_attempt_receipts_pending
    ON abuse_attempt_receipts (instance_key, pending_until)
    WHERE disposition = 'allow' AND resolved_outcome = '' AND default_outcome <> '';
`)
}

func PostgresSchemaDown() string {
	return strings.TrimSpace(`
DROP TABLE IF EXISTS abuse_attempt_receipts;
DROP TABLE IF EXISTS abuse_meter_states;
DROP TABLE IF EXISTS abuse_policy_definitions;
DROP TABLE IF EXISTS abuse_instances;
`)
}

func PostgresMigration(version int, up bool) (string, error) {
	if version != PostgresSchemaVersion {
		return "", fmt.Errorf("abuse: unsupported PostgreSQL schema version %d", version)
	}
	if up {
		return PostgresSchemaUp() + "\n", nil
	}
	return PostgresSchemaDown() + "\n", nil
}

func PostgresSchemaDigest(version int) (string, error) {
	up, err := PostgresMigration(version, true)
	if err != nil {
		return "", err
	}
	down, err := PostgresMigration(version, false)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(append([]byte(up), []byte(down)...))
	return hex.EncodeToString(sum[:]), nil
}

func WritePostgresMigration(directory, name string, version int) (WrittenPostgresMigration, error) {
	if strings.TrimSpace(directory) == "" {
		return WrittenPostgresMigration{}, errors.New("abuse: migration directory is required")
	}
	if strings.TrimSpace(name) == "" || filepath.Base(name) != name {
		return WrittenPostgresMigration{}, errors.New("abuse: migration name must be a base filename")
	}
	up, err := PostgresMigration(version, true)
	if err != nil {
		return WrittenPostgresMigration{}, err
	}
	down, err := PostgresMigration(version, false)
	if err != nil {
		return WrittenPostgresMigration{}, err
	}
	digest, err := PostgresSchemaDigest(version)
	if err != nil {
		return WrittenPostgresMigration{}, err
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return WrittenPostgresMigration{}, fmt.Errorf("abuse: create migration directory: %w", err)
	}
	header := fmt.Sprintf(
		"-- Code generated by foundation abuse; DO NOT EDIT.\n-- abuse-schema-version: %d\n-- abuse-schema-digest: %s\n\n",
		version, digest,
	)
	result := WrittenPostgresMigration{
		UpPath:   filepath.Join(directory, name+".up.sql"),
		DownPath: filepath.Join(directory, name+".down.sql"), Digest: digest,
	}
	if err := writeAbuseMigration(result.UpPath, []byte(header+up)); err != nil {
		return WrittenPostgresMigration{}, err
	}
	if err := writeAbuseMigration(result.DownPath, []byte(header+down)); err != nil {
		return WrittenPostgresMigration{}, err
	}
	return result, nil
}

func writeAbuseMigration(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil {
		if string(existing) == string(content) {
			return nil
		}
		return fmt.Errorf("abuse: migration drift at %s", path)
	}
	if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("abuse: read migration %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("abuse: write migration %s: %w", path, err)
	}
	return nil
}
