package siteprofile

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const CurrentPostgresSchemaVersion uint = 1
const DefaultPostgresPrefix = "site_profile_"

//go:embed schema/*.sql
var postgresSchemaFiles embed.FS

var postgresPrefixPattern = regexp.MustCompile(`^[a-z][a-z0-9_]{0,34}_$`)

type PostgresMigration struct {
	Version uint
	Prefix  string
	Digest  string
	UpSQL   string
	DownSQL string
}

type WrittenPostgresMigration struct {
	UpPath   string
	DownPath string
	Digest   string
}

func PostgresSchema(version uint, prefix string) (PostgresMigration, error) {
	if version != CurrentPostgresSchemaVersion {
		return PostgresMigration{}, fmt.Errorf("siteprofile: unsupported PostgreSQL schema version %d", version)
	}
	if prefix == "" {
		prefix = DefaultPostgresPrefix
	}
	if !postgresPrefixPattern.MatchString(prefix) {
		return PostgresMigration{}, fmt.Errorf("siteprofile: PostgreSQL prefix must match %s", postgresPrefixPattern)
	}
	up, err := postgresSchemaFiles.ReadFile("schema/v1.up.sql")
	if err != nil {
		return PostgresMigration{}, fmt.Errorf("siteprofile: read PostgreSQL up schema: %w", err)
	}
	down, err := postgresSchemaFiles.ReadFile("schema/v1.down.sql")
	if err != nil {
		return PostgresMigration{}, fmt.Errorf("siteprofile: read PostgreSQL down schema: %w", err)
	}
	up = []byte(strings.ReplaceAll(string(up), "{{prefix}}", prefix))
	down = []byte(strings.ReplaceAll(string(down), "{{prefix}}", prefix))
	sum := sha256.Sum256(append(append([]byte(nil), up...), down...))
	return PostgresMigration{
		Version: version, Prefix: prefix, Digest: hex.EncodeToString(sum[:]),
		UpSQL: string(up), DownSQL: string(down),
	}, nil
}

func WritePostgresMigration(directory, name string, version uint, prefix string) (WrittenPostgresMigration, error) {
	if strings.TrimSpace(directory) == "" {
		return WrittenPostgresMigration{}, errors.New("siteprofile: migration directory is required")
	}
	if strings.TrimSpace(name) == "" || filepath.Base(name) != name {
		return WrittenPostgresMigration{}, errors.New("siteprofile: migration name must be a base filename")
	}
	migration, err := PostgresSchema(version, prefix)
	if err != nil {
		return WrittenPostgresMigration{}, err
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return WrittenPostgresMigration{}, fmt.Errorf("siteprofile: create migration directory: %w", err)
	}
	header := fmt.Sprintf(
		"-- Code generated by foundation siteprofile; DO NOT EDIT.\n-- siteprofile-schema-version: %d\n-- siteprofile-schema-digest: %s\n\n",
		migration.Version, migration.Digest,
	)
	result := WrittenPostgresMigration{
		UpPath: filepath.Join(directory, name+".up.sql"), DownPath: filepath.Join(directory, name+".down.sql"),
		Digest: migration.Digest,
	}
	if err := writeImmutableMigration(result.UpPath, []byte(header+migration.UpSQL)); err != nil {
		return WrittenPostgresMigration{}, err
	}
	if err := writeImmutableMigration(result.DownPath, []byte(header+migration.DownSQL)); err != nil {
		return WrittenPostgresMigration{}, err
	}
	return result, nil
}

func writeImmutableMigration(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil {
		if string(existing) == string(content) {
			return nil
		}
		return fmt.Errorf("siteprofile: migration drift at %s", path)
	}
	if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("siteprofile: read migration %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("siteprofile: write migration %s: %w", path, err)
	}
	return nil
}
